### ISSUE TITLE
Controller Feature Request

### ISSUE THREAD

**Issue by DJ2695** [hadukin/custom_sliding_segmented_control#20]
It would be great to introduce some sort of controller in order to set the value of the SlidingSegmentedControl after e.g. you swiped in your PageView. Currently you can only set the Value once in initial Value.

**Comment by hadukin** [comment]
@DJ2695 Hi, starting from version 1.7.1, you can use CustomSegmentedController. You can also change the initialValue, which will allow you to change the value from the outside, you can see an example here: [https://github.com/hadukin/custom_sliding_segmented_control/pull/17](https://github.com/hadukin/custom_sliding_segmented_control/pull/17)
