### ISSUE TITLE
If isStretch, the background color not stratching.

### ISSUE THREAD

**Issue by LucreziaC** [hadukin/custom_sliding_segmented_control#21]
If isStretch, the background color not stratching. 

<img width="896" alt="Screenshot 2022-09-01 at 12 35 00" src="https://user-images.githubusercontent.com/37901017/187894292-75e4b251-7cf7-4719-bf91-cc6b9cd29f58.png">

_Originally posted by @LucreziaC in https://github.com/hadukin/custom_sliding_segmented_control/issues/6#issuecomment-1234086812_

**Comment by hadukin** [comment]
@LucreziaC  hi, I'll try to fix this, but I need more details. The slider version, and if possible the code that causes this problem.

**Comment by LucreziaC** [comment]
Sure!
The slider version is : 1.7.1
If application starts in portrait mode and then  is switched to landscape mode, the problem occurs as I notify you in my last comment. 
If application starts in landscape mode and then is switched to portrait mode, the background colour remains stretched.
The problem is also in your example class if I insert the isStretch field:

            CustomSlidingSegmentedControl<int>(
              controller: controller,
              isStretch: true,
              initialValue: initial,
              height: 24,
              children: {
                1: const Text('News daily portal'),
                2: const Text('Map'),
                3: const Text('Paper'),
                if (isPayment) 4: const Text('Metal Bord'),
              },
              decoration: BoxDecoration(
                color: CupertinoColors.lightBackgroundGray,
                borderRadius: BorderRadius.circular(8),
              ),
              thumbDecoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(6),
                boxShadow: [
                  BoxShadow(
                    color: Colors.black.withOpacity(.3),
                    blurRadius: 4.0,
                    spreadRadius: 1.0,
                    offset: const Offset(
                      0.0,
                      2.0,
                    ),
                  ),
                ],
              ),
              duration: const Duration(milliseconds: 300),
              curve: Curves.easeInToLinear,
              onValueChanged: (v) {
                controller.value = v;
                setState(() {
                  initial = v;
                });
              },
            ),

**Comment by hadukin** [comment]
@LucreziaC i will try to solve the problem as soon as I have free time

**Comment by hadukin** [comment]
@LucreziaC  hello, I fixed a bug in version 1.7.2

Thank you for helping to make the library even better

**Comment by arslan9380** [comment]
By Increasing the height thumb height is not increasing .
