### ISSUE TITLE
Thumb bugs when device orientation is changed

### ISSUE THREAD

**Issue by DreuDavids** [hadukin/custom_sliding_segmented_control#23]
@hadukin 
Thumb Decoration becomes offset from the appropriate position when a selection is made and device screen is rotated.

![Screenshot 2022-11-20 003546](https://user-images.githubusercontent.com/114517848/202874179-cb17d896-24a4-40b2-bb87-0ca4d7197089.png)

**Comment by hadukin** [comment]
@DreuDavids hi, what version are you using? I am not able to reproduce this problem, please attach the code and I will try to fix it

**Comment by DreuDavids** [comment]
I re ran the code today and seems like the problem might have been with the emulator.
cant reproduce the glitch anymore.

**Comment by hadukin** [comment]
not relevant
