### ISSUE TITLE
Hover does not use BoxConstraints

### ISSUE THREAD

**Issue by savadodesigns** [hadukin/custom_sliding_segmented_control#25]
Please see screenshot. Is there any way to fix this?

<img width="278" alt="Schermafbeelding 2023-01-24 om 17 07 34" src="https://user-images.githubusercontent.com/21218628/214345670-c4fa6940-b1b6-4b9c-a23c-d01beeb2003d.png">

**Comment by hadukin** [comment]
@savadodesigns hi, please add the code, I'll try to fix it

**Comment by savadodesigns** [comment]
```
CustomSlidingSegmentedControl(
  innerPadding: EdgeInsets.all(3),
  decoration: BoxDecoration(
    borderRadius: BorderRadius.circular(25),
    color: Colors.transparent,
  ),
  thumbDecoration: BoxDecoration(
    borderRadius: BorderRadius.circular(25),
    color: Colors.white,
  ),
  clipBehavior: Clip.hardEdge,
  initialValue: 'value',
  children: const {
    'value': Text('Current value'),
    'range': Text('Selected range'),
  },
  onValueChanged: (value) {
    sliderValue['measurements'] = value;
    apiLoaded.value = value;
  },
)
```

**Comment by hadukin** [comment]
@savadodesigns hi, i added more slider customization options in version 1.7.4, now it will be possible to customize the display of segments on hover, it will also be possible to handle hover using the `onHoverSegment` function

I hope this helps you)

custom_sliding_segmented_control: ^1.7.4

You can see an example here:
https://github.com/hadukin/custom_sliding_segmented_control/blob/main/example/lib/example_11.dart

**Comment by savadodesigns** [comment]
@hadukin Wow, that was really quick! Thank you very much.
<img width="281" alt="Schermafbeelding 2023-01-26 om 15 14 06" src="https://user-images.githubusercontent.com/21218628/214858102-a276ec76-13cb-4467-9998-ce351e4934d8.png">
