### ISSUE TITLE
Set text color of selected segment

### ISSUE THREAD

**Issue by martijndierckx** [hadukin/custom_sliding_segmented_control#27]
How should I set the text color of the selected item?

**Comment by hadukin** [comment]
@martijndierckx hi, one way to do this

`
int current = 0;

  @override
  Widget build(BuildContext context) {
    return CustomSlidingSegmentedControl<int>(
      isStretch: true,
      initialValue: 2,
      height: 24,
      children: {
        0: Text(
          'News daily portal',
          style: TextStyle(color: current == 0 ? Colors.red : Colors.black),
        ),
        1: Text(
          'Map',
          style: TextStyle(color: current == 1 ? Colors.red : Colors.black),
        ),
        2: Text(
          'Paper',
          style: TextStyle(color: current == 2 ? Colors.red : Colors.black),
        ),
      },
      decoration: BoxDecoration(
        color: CupertinoColors.lightBackgroundGray,
        borderRadius: BorderRadius.circular(8),
      ),
      thumbDecoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(6),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(.3),
            blurRadius: 4.0,
            spreadRadius: 1.0,
            offset: const Offset(
              0.0,
              2.0,
            ),
          ),
        ],
      ),
      duration: const Duration(milliseconds: 300),
      curve: Curves.easeInToLinear,
      onValueChanged: (v) {
        setState(() {
          current = v;
        });
      },
    );
  }
`
