### ISSUE TITLE
divider between segment

### ISSUE THREAD

**Issue by Coin-ai** [hadukin/custom_sliding_segmented_control#28]
hi , is it possible to have vertical divider? thanks

**Comment by EeeDotZee** [comment]
would appreciate that aswell!! Thank you

**Comment by hyped0001** [comment]
bump @hadukin <3

**Comment by adnanjpg** [comment]
hey, any progress on this? @hadukin if you don't have the time I'd love to get this done

**Comment by aanari** [comment]
https://github.com/hadukin/custom_sliding_segmented_control/pull/33

**Comment by hadukin** [comment]
Hello everyone 🙌 thanks for the long wait, I finally added support for divider in version 1.8.0 🥳🥳🥳
