### ISSUE TITLE
how to manage disabled state for each segment

### ISSUE THREAD

**Issue by itsmeemaaario-student** [hadukin/custom_sliding_segmented_control#34]
`isDisabled` flag disables the whole widget. However, what if we want to disable a single control? 

Let's say we have a CustomSlidingSegmentedControl with 3 children and we need to disable the last one, while the rest remain active.

Is there a way I'm missing? For now, it seems there's no way to stop the internal state and the animation. If not, could you please add this as a new feature? Thank you.

**Comment by hadukin** [comment]
@itsmeemaaario-student hi, I will try to add this functionality soon

**Comment by tologonkudaiberdiuulu** [comment]
@hadukin Hi. Any progress?
