### ISSUE TITLE
Divider: configure height and for which items should be displayed

### ISSUE THREAD

**Issue by adnanjpg** [hadukin/custom_sliding_segmented_control#36]
Hey,

I am trying to apply the following design using this package:
<img width="575" alt="Screenshot 2023-10-13 at 11 09 37 PM" src="https://github.com/hadukin/custom_sliding_segmented_control/assets/54329101/747f367c-d91c-4e56-9648-1d3b8e3a0173">

The current state of the divider results in the following result:
<img width="302" alt="Screenshot 2023-10-13 at 11 10 09 PM" src="https://github.com/hadukin/custom_sliding_segmented_control/assets/54329101/896ecd20-ab36-4f22-98d6-b72496c3cd9e">

To match such custom designs there should be a way to configure the height of the divider and to configure after which items it should be displayed

**Comment by adnanjpg** [comment]
I'm trying to work on these

I've added a solution for configuring the "height". adding a height would not work because it's not possible to limit the height entered by the user, in a case where the user does not know the box's height, it's hard for them to know how much the height of the divider should be. so instead, I found it would be better to add a "verticalMargin" property. Please checkout the progress I've done:
https://github.com/adnanjpg/custom_sliding_segmented_control/commit/b99245713eba472ef8f3c89b8b6118e0c6ceb177

**Comment by hadukin** [comment]
@adnanjpg hi, thanks for the suggestion, this option can also be considered, but I don’t understand how it would differ from indent and endIndent

**Comment by hadukin** [comment]
@adnanjpg can you post the code here so I can see how to fix this?

**Comment by adnanjpg** [comment]
> but I don’t understand how it would differ from indent and endIndent
Oh actually it appears that indent and endindent would fix this problem, there was a misunderstanding on my end, sorry for the confusion

**Comment by adnanjpg** [comment]
as for

> configure after which items it should be displayed

I'm not sure what kind of API would offer the most convenient DX for this one

**Comment by hadukin** [comment]
@adnanjpg hi, i made some changes to version 1.8.1, maybe this is what you need)
If your problem is solved in version 1.8.1 please close this PR
