### ISSUE TITLE
how can I change the color of the corners?

### ISSUE THREAD

**Issue by KirbyRedius** [hadukin/custom_sliding_segmented_control#39]
How can I change the color of the corners?

![image](https://github.com/hadukin/custom_sliding_segmented_control/assets/136841386/56428392-0e03-48b1-9977-3779f8d300cb)

**Comment by hadukin** [comment]
@KirbyRedius hi, please add sample code so I can reproduce the problem

**Comment by Hilbert2048** [comment]
I have a similar question, when click a segment (with radius)

**Comment by Hilbert2048** [comment]
fix by specifying the radius of CustomSegmentSettings :

      customSegmentSettings: CustomSegmentSettings(
        radius: XXX,
      ),
