### ISSUE TITLE
Weird separator behavior in RTL mode

### ISSUE THREAD

**Issue by anprut** [hadukin/custom_sliding_segmented_control#40]
When the app is in RTL mode, the separator position is incorrect.

Preview:

https://github.com/hadukin/custom_sliding_segmented_control/assets/161455323/6730fea7-11ba-46c5-81ee-26c52974bbe0

When `isHideAutomatically: false`

https://github.com/hadukin/custom_sliding_segmented_control/assets/161455323/b8de5be5-909e-44ff-942c-e7cdb2ed6d9b

**Comment by anatolykirsanov** [comment]
@anprut hi, thanks, I will try to solve the problem

**Comment by hadukin** [comment]
@anprut hi, fixed it in version 1.8.2
