### ISSUE TITLE
change height of the thumb

### ISSUE THREAD

**Issue by piringhologram** [hadukin/custom_sliding_segmented_control#41]
![image](https://github.com/hadukin/custom_sliding_segmented_control/assets/68436465/2a3af5bb-3df2-4312-95cd-3b1aaa0152ed)

How can i change the height of the thumb according to the children element's size ? i have been looking around the documentation for a while and i haven't found a solution.

**Comment by anatolykirsanov** [comment]
@piringhologram hi, please add a sample code to reproduce the problem.
