### ISSUE TITLE
How to grow size of SegmentedButtons?

### ISSUE THREAD

**Issue by ahmetakay24** [hadukin/custom_sliding_segmented_control#43]
<img width="377" alt="Screenshot at May 27 20-26-36" src="https://github.com/hadukin/custom_sliding_segmented_control/assets/112816543/0baeff45-a052-455b-9107-bdfd3aa15d18">

Code = class MainScreen extends StatelessWidget {
  MainScreen({super.key});

  final AppColors colors = AppColors();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: CustomAppBar(context: context),
      body: Padding(
        padding: const EdgeInsets.only(top: 20, left: 15, right: 15),
        child: Column(
          children: [
            Row(
              crossAxisAlignment: CrossAxisAlignment.center,
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                ElevatedButton(
                  onPressed: () {},
                  style: ElevatedButton.styleFrom(padding: const EdgeInsets.symmetric(horizontal: 40)),
                  child: const Text("Bus"),
                ),
                ElevatedButton(onPressed: () {}, child: const Text("Aeroplane")),
                ElevatedButton(
                  onPressed: () {},
                  style: ElevatedButton.styleFrom(
                    padding: const EdgeInsets.symmetric(horizontal: 35),
                  ),
                  child: const Text("Train"),
                )
              ],
            ),
            Padding(
              padding: const EdgeInsets.only(top: 20),
              child: Container(
                height: MediaQuery.of(context).size.height * 0.5,
                width: MediaQuery.of(context).size.width,
                decoration: BoxDecoration(color: colors.lightBlueColor, borderRadius: BorderRadius.circular(60)),
                child: Column(
                  children: [
                    Padding(
                      padding: const EdgeInsets.only(top: 20),
                      child: CustomSlidingSegmentedControl<int>(
                        initialValue: 2,
                        children: const {
                          1: Text('One Way'),
                          2: Text('Round Trip'),
                          3: Text('Multicity'),
                        },
                        decoration: BoxDecoration(
                          color: colors.blueColor,
                          borderRadius: BorderRadius.circular(20),
                        ),
                        thumbDecoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: BorderRadius.circular(20),
                          boxShadow: [
                            BoxShadow(
                              color: Colors.black.withOpacity(.3),
                              blurRadius: 4.0,
                              spreadRadius: 1.0,
                              offset: const Offset(
                                0.0,
                                2.0,
                              ),
                            ),
                          ],
                        ),
                        duration: const Duration(milliseconds: 300),
                        curve: Curves.easeInToLinear,
                        onValueChanged: (v) {
                          print(v);
                        },
                      ),
                    )
                  ],
                ),
              ),
            )
          ],
        ),
      ),
    );
  }
}

**Comment by hadukin** [comment]
@ahmetakay24 hi, you can use the parameter `isStretch: true`

**Comment by WolfspiritM** [comment]
@hadukin While "isStretch" stretches all buttons the same. Is there any way to set one button to a fixed size and let the other buttons share the rest of the space? For example I have one button at the start which is an icon which should always have the same size while the rest of the buttons are text and they should share the remaining space.
