### ISSUE TITLE
Full width segmented control

### ISSUE THREAD

**Issue by luis-cruzt** [hadukin/custom_sliding_segmented_control#6]
Hi, is there any way to expand the items with the parent container of the segmented control just like this?

![image](https://user-images.githubusercontent.com/55716036/121097881-5cd15800-c7ba-11eb-92fb-d4be0a2c6b98.png)

**Comment by luis-cruzt** [comment]
@hadukin ?

**Comment by BLKKKBVSIK** [comment]
@hadukin Any update on this?

**Comment by hadukin** [comment]
@luis-cruzt hi, at the moment, this option is not available. I'll think about how to do this.

**Comment by luis-cruzt** [comment]
It will be great if you could find how to achieve this, i've already tried but with no success.

**Comment by hadukin** [comment]
@luis-cruzt , i added a new bool parameter `isStretch`, now it will work ;)

**Comment by LucreziaC** [comment]
If isStretch, the background color not stratching. 

<img width="896" alt="Screenshot 2022-09-01 at 12 35 00" src="https://user-images.githubusercontent.com/37901017/187894292-75e4b251-7cf7-4719-bf91-cc6b9cd29f58.png">
