### ISSUE TITLE
Different color of text for selected item.

### ISSUE THREAD

**Issue by mefuzar** [hadukin/custom_sliding_segmented_control#7]
Is it possible to have a different text color for the selected item?

The following did not work for me :(

Could you please assist?

`CustomSlidingSegmentedControl<int>(
  children: {
        0: Text("First", style: TextStyle(color: _currentSegment == 0 ? CupertinoColors.activeBlue : CupertinoColors.systemRed)),
        1: Text("Second", style: TextStyle(color: _currentSegment == 1 ? CupertinoColors.activeBlue : CupertinoColors.systemRed)),
      },
      // ...
      onValueChanged: (int index) {
        print("currentSegment is: $index");
        _currentSegment = index;
      },
    ),`

**Comment by hadukin** [comment]
Hi @mefuzar, in `onValueChanged` you need to call setState
`
onValueChanged(int index) {
  setState(() {
    _currentSegment = index;
  });
}
`
