### ISSUE TITLE
Selected tab animates to correct position on appear

### ISSUE THREAD

**Issue by nishiths23** [hadukin/custom_sliding_segmented_control#8]
If you have 3 tabs on a page and the pre selected is 3rd tab.

 In this case when you navigate to this page from another page the tab starts from first index and then animated to the 3rd.

Which looks weird because as soon as the page opens there is an animation.

https://user-images.githubusercontent.com/16319917/129372637-d858204e-aaa4-493e-a65f-5db4d6403973.mp4

**Comment by hadukin** [comment]
@nishiths23 hi, i fixed animation when switching between screens
